name: CD Functions

on:
  push: # 커밋이 푸시됬을때
    branches: 
      - main # 메인브랜치에
    paths:
      - "functions/**" # functions폴더 밑의 파일이 수정되었을때

jobs:
  build-and-deploy:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: ["16"]
    name: Node ${{ matrix.node }} (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        working-directory: functions

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: 패키지 설치
        run: |
          yarn
          yarn build

      - name: 파이어베이스 툴 설치
        run: npm i firebase-tools -g 
          
      - name: 파이어베이스 functions 배포
        run: firebase deploy --only functions --token ${{ secrets.FIREBASE_DEPLOY_TOKEN }}